version: "3"

includes:
  lint: "./taskfiles/lint.yaml"
  tests: "./taskfiles/tests.yaml"
  utils: "./exports/taskfiles/utils/utils.yaml"

set: ["u", "pipefail"]
shopt: ["globstar"]

vars:
  G_OUTPUT_DIR: "{{.ROOT_DIR}}/build"

tasks:
  clean:
    cmds:
      - "rm -rf '{{.G_OUTPUT_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_OUTPUT_DIR}}'"

  test:
    cmds:
      - task: "tests:all"
