version: "3"

includes:
  lint: "./taskfiles/lint/main.yaml"
  tests: "./taskfiles/tests.yaml"

set: ["u", "pipefail"]
shopt: ["globstar"]

vars:
  G_OUTPUT_DIR: "{{.ROOT_DIR}}/build"

tasks:
  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_OUTPUT_DIR}}'"

  clean:
    cmds:
      - "rm -rf '{{.G_OUTPUT_DIR}}'"

  test:
    cmds:
      - task: "tests:all"
