version: "3"

includes:
  lint: "./taskfiles/lint/main.yaml"
  tests: "./taskfiles/tests.yaml"

set: ["u", "pipefail"]
shopt: ["globstar"]

vars:
  # Directories
  G_EXPORTS_DIR: "{{.ROOT_DIR}}/exports"
  G_LINT_CONFIGS_DIR: "{{.G_EXPORTS_DIR}}/lint-configs"
  G_OUTPUT_DIR: "{{.ROOT_DIR}}/build"
  G_YSTDLIB_PY_DIR: "{{.G_EXPORTS_DIR}}/ystdlib-py"

  # Utility commands
  G_PYFIND_CMD: "uv run --project '{{.G_YSTDLIB_PY_DIR}}' pyfind"

tasks:
  clean:
    cmds:
      - "rm -rf '{{.G_OUTPUT_DIR}}'"

  test:
    cmds:
      - task: "tests:all"

  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_OUTPUT_DIR}}'"
