# Created based on v1.35.1
# NOTE:
# - Rules are only configured if they differ from the default configuration.
# - Users should use `yamllint` with the `--strict` option to treat warnings as errors.

extends: "default"

yaml-files:
  - ".clang-format"
  - ".yamllint"
  - "*.yaml"
  - "*.yml"

rules:
  anchors:
    # Disabled so that we can reference aliases that exist later in the file
    forbid-undeclared-aliases: false

  braces:
    max-spaces-inside-empty: 0
    min-spaces-inside-empty: 0

  brackets:
    max-spaces-inside-empty: 0
    min-spaces-inside-empty: 0

  comments:
    level: "error"
    # Disabled so that snippets can be uncommented easily
    require-starting-space: false

  document-end:
    present: false

  document-start:
    present: false

  empty-lines:
    max: 1

  float-values:
    require-numeral-before-decimal: true

  indentation:
    spaces: 2

  line-length:
    allow-non-breakable-words: true
    max: 100

  octal-values:
    forbid-explicit-octal: false
    forbid-implicit-octal: true

  quoted-strings:
    quote-type: "double"

  truthy:
    # Disabled for keys since GitHub actions uses the truthy-looking key "on"
    check-keys: false
