name: "Print tool versions"
description: "Print tool versions to aid debugging in case of CI failures."

runs:
  using: "composite"
  steps:
    - name: "Print tool versions"
      shell: "bash"
      env:
        TOOLS: |-
          cc
          c++
          cmake
          md5sum
          python
          python3
          tar
          task
          uv
      run: |-
        while IFS= read -r tool; do
          if ! "${tool}" --version; then
            echo "${tool} not found"
          fi
        done <<< "${TOOLS}"
